services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: productsdb
    ports:
      - "5443:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro

  app:
    build: .
    image: batch-processing-api
    depends_on:
      - postgresdb
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/productsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456


