services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: productsdb
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro

  app:
    depends_on:
      - postgresdb
    image: batch-processing
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: no